name: Verify Version Bump

on:
  pull_request:
    branches: [main]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: rayepps/require-semver-bump@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          file: package.json
          pattern: >
            \\"version\\":\s\\"(.+?)\\"
